version: '3.5'
services:

  app:
    build: .
    image: &app app
    restart: "no"
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./appdata:/appdata
    env_file: &envfile
      - env.env
    ports:
      - "8000:8000"
    depends_on:
      - broker

  worker:
    build: .
    image: *app
    restart: "no"
    command: ["celery", "-A","DNA_form","worker", "-l", "info"]
    volumes:
      - ".:/app:rw"
    depends_on:
      - broker

  broker:
    image: rabbitmq:3
    command: ["rabbitmq-server"]
    volumes:
      - ".:/app:rw"
    env_file: *envfile
    ports:
      - 5672:5672
